### ISSUE TITLE
Bounding box from IPT is incorrectly interpreted on the dataset page

### ISSUE THREAD

**Issue by jlegind** [gbif/maps#24] opened 2017-11-06 14:03 UTC
While the coordinate box shape looks correct in the IPT, the two coordinate points it passes on to GBIF seem to be interpreted as going from -180 and towards East. That is going from the most Westwards point and moving towards East regardless of the coordinate label.
`<westBoundingCoordinate>-18.984</westBoundingCoordinate>
          <eastBoundingCoordinate>-168.047</eastBoundingCoordinate>
          <northBoundingCoordinate>78.768</northBoundingCoordinate>
          <southBoundingCoordinate>-36.031</southBoundingCoordinate>`
 In that regard our interpretation is ‘stupid’ since it cannot figure out that bounding boxes can cross the antipodal meridian.

http://gbif.ru:8080/ipt/resource?r=raptors
https://www.gbif.org/dataset/b941d3d1-964e-47dc-a3e7-f8edb144e051#geographicCoverages

**Comment by MortenHofft** [comment] 2017-11-06 14:41
closed as duplicate of https://github.com/gbif/portal-feedback/issues/635

**Closed by MortenHofft** 2017-11-06 14:41 UTC
